/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrnagaiCreator.java
 *
 * Created on Sep 10, 2009, 1:10:13 AM
 */

package ornagai.mobile.tools;

import java.awt.Color;

/**
 *
 * @author Seth N. Hetu
 */
public class OrnagaiCreator extends javax.swing.JApplet {


    /** Initializes the applet OrnagaiCreator */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    getContentPane().setBackground(getBackground()); //Weird...
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstPnl = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        lblSampleEntry = new javax.swing.JLabel();
        lblSample = new javax.swing.JLabel();
        cmbStructPOS = new javax.swing.JComboBox();
        cmbStructDef = new javax.swing.JComboBox();
        lblDefinition = new javax.swing.JLabel();
        cmbStructWord = new javax.swing.JComboBox();
        lblStructPOS = new javax.swing.JLabel();
        btnBrowseForDict = new javax.swing.JButton();
        txtPathToDictionary = new javax.swing.JTextField();
        lblChooseFile = new javax.swing.JLabel();
        lblCurrentPage = new javax.swing.JLabel();
        lblStructWord = new javax.swing.JLabel();
        lblStructure = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setName("firstPnl"); // NOI18N

        firstPnl.setOpaque(false);
        firstPnl.setPreferredSize(new java.awt.Dimension(463, 421));

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.setEnabled(false);

        lblSampleEntry.setBackground(new java.awt.Color(255, 255, 255));
        lblSampleEntry.setFont(new java.awt.Font("Zawgyi-One", 0, 12)); // NOI18N
        lblSampleEntry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSampleEntry.setText("<html><div style=\"background:#DDDDDD; width:142px; height:87px;\"><b>scion</b><br><i>n</i><br>\u1021\u1019\u103A\u102D\u102F\u1038\u1031\u1000\u102C\u1004\u1039\u1038\u101E\u102C\u1038\u104B \u1019\u103A\u102D\u102F\u1038\u1006\u1000\u1039\u104B \u1021\u1015\u1004\u1039\u1015\u103C\u102C\u1038\u101A\u1030\u101B\u1014\u1039\u103B\u1016\u1010\u1039\u1011\u102F\u1010\u1039\u101E\u100A\u1039&shy;\u1037\u1015\u1004\u1039\u1005\u100A\u1039\u1021\u1015\u102D\u102F\u1004\u1039\u1038\u1021\u1005\u104B \u1015\u1004\u1039\u1015\u103C\u102C\u1038\u1019\u103A\u102D\u102F\u1038\u1006\u1000\u1039\u104B</div></html>");
        lblSampleEntry.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSampleEntry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lblSampleEntry.setOpaque(true);

        lblSample.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSample.setText("Sample:");

        cmbStructPOS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbStructPOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Column 1", "Column 2", "Column 3" }));
        cmbStructPOS.setSelectedIndex(1);
        cmbStructPOS.setEnabled(false);

        cmbStructDef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbStructDef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Column 1", "Column 2", "Column 3" }));
        cmbStructDef.setSelectedIndex(2);
        cmbStructDef.setEnabled(false);

        lblDefinition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDefinition.setText("Definition:");

        cmbStructWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbStructWord.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Column 1", "Column 2", "Column 3" }));
        cmbStructWord.setEnabled(false);

        lblStructPOS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStructPOS.setText("P.O.S.:");

        btnBrowseForDict.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBrowseForDict.setText("...");

        txtPathToDictionary.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtPathToDictionary.setText("D:\\Open Source Projects\\ornagai_dict\\NEW! dictionary (tsv) 2008\\convert_entab.tsv");

        lblChooseFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChooseFile.setText("Choose your dictionary:");

        lblCurrentPage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCurrentPage.setForeground(new java.awt.Color(153, 153, 153));
        lblCurrentPage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurrentPage.setText("<html><span style=\"font-weight: bold; color:black; font-size:26pt;\">1</span>..2..3</html>");

        lblStructWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStructWord.setText("Word:");

        lblStructure.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStructure.setText("Dictionary Structure:");

        javax.swing.GroupLayout firstPnlLayout = new javax.swing.GroupLayout(firstPnl);
        firstPnl.setLayout(firstPnlLayout);
        firstPnlLayout.setHorizontalGroup(
            firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPnlLayout.createSequentialGroup()
                        .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstPnlLayout.createSequentialGroup()
                                .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(firstPnlLayout.createSequentialGroup()
                                        .addComponent(lblStructWord)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbStructWord, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPathToDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(firstPnlLayout.createSequentialGroup()
                                        .addComponent(lblStructPOS)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbStructPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(firstPnlLayout.createSequentialGroup()
                                        .addComponent(lblDefinition)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbStructDef, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addComponent(btnBrowseForDict, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(lblStructure)
                            .addGroup(firstPnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblSampleEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(firstPnlLayout.createSequentialGroup()
                                .addComponent(lblSample)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)
                        .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrentPage)))
                    .addComponent(lblChooseFile))
                .addContainerGap())
        );
        firstPnlLayout.setVerticalGroup(
            firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPnlLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(firstPnlLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblChooseFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBrowseForDict, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPathToDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblStructure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbStructWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStructWord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbStructPOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStructPOS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(firstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbStructDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDefinition))
                        .addGap(16, 16, 16)
                        .addComponent(lblSample)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSampleEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(firstPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(firstPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentPage)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseForDict;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox cmbStructDef;
    private javax.swing.JComboBox cmbStructPOS;
    private javax.swing.JComboBox cmbStructWord;
    private javax.swing.JPanel firstPnl;
    private javax.swing.JLabel lblChooseFile;
    private javax.swing.JLabel lblCurrentPage;
    private javax.swing.JLabel lblDefinition;
    private javax.swing.JLabel lblSample;
    private javax.swing.JLabel lblSampleEntry;
    private javax.swing.JLabel lblStructPOS;
    private javax.swing.JLabel lblStructWord;
    private javax.swing.JLabel lblStructure;
    private javax.swing.JTextField txtPathToDictionary;
    // End of variables declaration//GEN-END:variables

}
